apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    acme.cert-manager.io/http01-edit-in-place: "true"
    kubernetes.io/ingress.class: public
spec:
  tls:
  - hosts:
    - webtrees.apps.sambriggs.dev
    - quayfm.apps.sambriggs.dev
    secretName: apps-tls
  rules:
  - host: webtrees.apps.sambriggs.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webtrees
            port:
              number: 80
  - host: quayfm.apps.sambriggs.dev
    http:
      paths:
      - path: /live
        pathType: Exact
        backend:
          service:
            name: quayfm-proxy
            port:
              number: 1071
