apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: haproxy
  name: proxy
spec:
  rules:
  - host: "apps.sambriggs.dev"
    http:
      paths:
      - backend:
          serviceName: webtrees
          servicePort: 80
        path: /
