apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: http-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  tls:
  - hosts:
    - webtrees.apps.sambriggs.dev
    secretName: apps-tls
  rules:
  - host: webtrees.apps.sambriggs.dev
    http:
      paths:
      - path: /
        backend:
          serviceName: webtrees
          servicePort: 80
