apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: haproxy
    # TLS issuer
    certmanager.io/cluster-issuer: letsencrypt
  name: proxy
spec:
  rules:
  - host: "apps.sambriggs.dev"
    http:
      paths:
      - backend:
          service:
            name: webtrees
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - # cert-manager will store the certificate and key in this secret
    secretName: mysite-cert 
    hosts:
    - apps.sambriggs.dev
