apiVersion: v1
kind: Service
metadata:
  name: webtrees
  labels:
    app: webtrees
spec:
  ports:
    - port: 80
  selector:
    app: webtrees
    tier: frontend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wt-pv-claim-data
  labels:
    app: webtrees
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wt-pv-claim-media
  labels:
    app: webtrees
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: webtrees
  labels:
    app: webtrees
spec:
  selector:
    matchLabels:
      app: webtrees
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webtrees
        tier: frontend
    spec:
      containers:
      - image: briggysmalls/personal-webtrees:latest
        name: webtrees
        env:
        - name: BASE_URL
          value: https://webtrees.apps.sambriggs.dev
        - name: DB_TYPE
          value: mysql
        - name: DB_HOST
          value: webtrees-mysql
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-user
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: mysql-user
              key: password
        - name: PRETTY_URLS
          value: "true"
        - name: LANG
          value: en-GB
        - name: WT_NAME
          valueFrom:
            secretKeyRef:
              name: webtrees-admin
              key: name
        - name: WT_USER
          valueFrom:
            secretKeyRef:
              name: webtrees-admin
              key: username
        - name: WT_PASS
          valueFrom:
            secretKeyRef:
              name: webtrees-admin
              key: password
        - name: WT_EMAIL
          valueFrom:
            secretKeyRef:
              name: webtrees-admin
              key: email
        ports:
        - containerPort: 80
          name: webtrees
        volumeMounts:
        - name: webtrees-persistent-storage-data
          mountPath: /var/www/webtrees/data/
        - name: webtrees-persistent-storage-media
          mountPath: /var/www/webtrees/media/
      volumes:
      - name: webtrees-persistent-storage-data
        persistentVolumeClaim:
          claimName: wt-pv-claim-data
      - name: webtrees-persistent-storage-media
        persistentVolumeClaim:
          claimName: wt-pv-claim-media
